version: 0.2

phases:
  build:
    commands:
      - mvn clean install -P quick
      - cd test/sdk-benchmarks
      - mvn package
      - java -jar target/benchmarks.jar ApiCallHttpClientBenchmark ClientCreationBenchmark
