version: 0.2

phases:
  build:
    commands:
      - mvn clean install -P quick -pl :sdk-benchmarks --am
      - cd test/sdk-benchmarks
      - declare -a BENCH_MARKS
      - |
        if git diff --name-only master HEAD | grep -q "http-clients/"; then
          echo "Found changes in http-clients, will run ApiCallHttpClientBenchmark"
          BENCH_MARKS+=( ApiCallHttpClientBenchmark )
        fi
      - |
        if git diff --name-only master HEAD | grep -q "core/"; then
          echo "Found changes in core, will run ApiCallProtocolBenchmark and ClientCreationBenchmark"
          BENCH_MARKS+=( ApiCallProtocolBenchmark )
          BENCH_MARKS+=( ClientCreationBenchmark )
        fi
      - |
        if [ ${#BENCH_MARKS[@]} -eq 0 ]; then
          echo "No benchmarks to run"
        else
          echo "Running the following benchmarks, ${BENCH_MARKS[@]"
          java -jar target/benchmarks.jar ${BENCH_MARKS[@]}