version: 0.2

phases:
  build:
    commands:
      - mvn clean install -P quick -pl :sdk-benchmarks --am
      - cd test/sdk-benchmarks
      - mvn exec:exec -Dbenchmarks=ClientCreationBenchmark
      - /bin/bash ../../buildspecs/runBenchmarks.sh